# services.core package
from .config import (
    OPENAI_API_KEY,
    DATABASE_URL,
    EMBEDDING_DIM,
    LOCAL_EMBEDDING_MODEL_SBERT,
    CHAT_PROVIDER,
    CHAT_MODEL,
    OPENAI_CHAT_MODEL,
    OLLAMA_CHAT_MODEL,
    OLLAMA_BASE_URL,
    FAISS_INDEX_PATH,
    RERANKER_ENABLED,
    RERANKER_MODEL,
    RERANKER_TOP_K,
)

__all__ = [
    "OPENAI_API_KEY",
    "DATABASE_URL",
    "EMBEDDING_DIM",
    "LOCAL_EMBEDDING_MODEL_SBERT",
    "CHAT_PROVIDER",
    "CHAT_MODEL",
    "OPENAI_CHAT_MODEL",
    "OLLAMA_CHAT_MODEL",
    "OLLAMA_BASE_URL",
    "FAISS_INDEX_PATH",
    "RERANKER_ENABLED",
    "RERANKER_MODEL",
    "RERANKER_TOP_K",
]
