# services.core package
from .config import (
    DATABASE_URL,
    EMBEDDING_DIM,
    LOCAL_EMBEDDING_MODEL_SBERT,
    CHAT_MODEL,
    OLLAMA_CHAT_MODEL,
    OLLAMA_BASE_URL,
    FAISS_INDEX_PATH,
)

__all__ = [
    "DATABASE_URL",
    "EMBEDDING_DIM",
    "LOCAL_EMBEDDING_MODEL_SBERT",
    "CHAT_MODEL",
    "OLLAMA_CHAT_MODEL",
    "OLLAMA_BASE_URL",
    "FAISS_INDEX_PATH",
]
